Traceback (most recent call last):
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from CrocoDash.case import Case

case = Case(
    cesmroot = cesmroot,
    caseroot = caseroot,
    inputdir = inputdir,
    ocn_grid = grid,
    ocn_vgrid = vgrid,
    ocn_topo = topo,
    project = 'NCGD0011',
    override = True,
    machine = "derecho",
    compset = "1850_DATM%JRA_SLND_SICE_MOM6_SROF_SGLC_SWAV"
)
------------------

----- stderr -----
WARNING:  cime_interface:CIME_OUTPUT_ROOT doesn't exist. Creating it at /home/runner/cesm/scratch
----- stderr -----
ERROR:  cime_interface:DIN_LOC_ROOT doesn't exist: /home/runner/cesm/inputdata
----- stderr -----
INFO:  csp_solver:CspSolver initialized.
----- stdout -----
[01;96mCreating case...[0m

â€¢ Updating ccs_config/modelgrid_aliases_nuopc.xml file to include the new resolution "panama-not" consisting of the following component grids.
 atm grid: "TL319", lnd grid: "TL319", ocn grid: "panama1".

â€¢ Updating ccs_config/component_grids_nuopc.xml file to include newly generated ocean grid "panama1" with the following properties:
 nx: 300, ny: 300. ocean mesh: /home/runner/croc_input/panama-not/ocnice/ESMF_mesh_panama1_a94c7b.nc.[0m

[01;96mRunning the create_newcase tool with the following command:[0m

/home/runner/work/CrocoGallery/CrocoGallery/CESM/cime/scripts/create_newcase --compset 1850_DATM%JRA_SLND_SICE_MOM6_SROF_SGLC_SWAV --res panama-not --case /home/runner/croc_cases/panama-not --machine derecho --run-unsupported --project NCGD0011 --non-local
----- stdout -----
[1;31mError creating case.[0m

b"ERROR: Undefined env var 'SCRATCH'\n"

[1;31mError creating case.[0m
------------------

An exception has occurred, use %tb to see the full traceback.

[0;31mCIMEError[0m[0;31m:[0m ERROR: Makes no sense to have empty read-only file: /home/runner/croc_cases/panama-not/env_case.xml


